name: obtainium
description: Get Android app updates straight from the source.
publish_to: 'none'

version: 1.6.0+2339

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  path_provider: ^2.1.6
  flutter_fgbg: ^0.8.0
  flutter_local_notifications: ^22.0.1
  provider: ^6.1.5+1
  http: ^1.6.0
  webview_flutter: ^4.14.0
  dynamic_system_colors: ^1.9.0
  html: ^0.15.6
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  url_launcher: ^6.3.2
  permission_handler: ^12.0.3
  fluttertoast: ^9.1.0
  device_info_plus: ^13.2.0
  file_picker: ^12.0.0-beta.7
  animations: ^2.2.0
  android_package_installer: # TODO: See if PR will be accepted (dev may not be active), else remove this comment
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: c9e144fae63231b5d1d7b88af779c314afcb6e83
  android_package_manager: # TODO: Make PR and switch to upstream
    git:
      url: https://github.com/ImranR98/android_package_manager
      ref: 18231a8a2343747440b0bfe90f7d56ef7f586099
  share_plus: ^13.2.0
  sqflite: ^2.4.3
  easy_localization: ^3.0.8
  intl: ^0.20.2
  android_intent_plus: ^6.0.0
  flutter_archive: ^6.3.1
  archive: ^4.0.9
  hsluv: ^1.1.3
  connectivity_plus: ^7.2.0
  shared_storage: # TODO: Is this maintained?
    git:
      url: https://github.com/AlexBacich/shared-storage
      ref: 6dbcdf2c2045e326f59c062f542724aedf73cb6e
  crypto: ^3.0.7
  bcrypt: ^1.2.0
  app_links: ^7.2.0
  background_fetch: ^1.7.0
  equations: ^6.0.0
  flex_color_picker: ^3.8.0
  android_system_font:
    git:
      url: https://github.com/re7gog/android_system_font
      ref: 077e15d7d0acb82283b89dfd82f4984b27b28f95
  shizuku_apk_installer:
    git:
      url: https://github.com/re7gog/shizuku_apk_installer
      ref: 3ef7f8fbf904848d144304556b0f80c91fee82a5
  markdown: ^7.3.1
  flutter_typeahead: ^6.0.0
  battery_plus: ^7.1.0
  flutter_charset_detector: ^6.0.0

  flutter_foreground_task: ^9.2.2
  flutter_markdown_plus: ^1.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/graphics/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/graphics/
    - assets/ca/

  fonts:
      - family: Montserrat
        fonts:
          - asset: assets/fonts/Montserrat-Regular.ttf
