name: Validate Fastlane metadata

on:
  workflow_dispatch:
  push:
      branches: [ "main" ]
  pull_request:
      branches: [ "main" ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - name: Validate Fastlane Supply Metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@c8857fdbbd3e00f9a5cbe8604bcecfa95ce8fef8 # v2.1.0
