name: Validate translation files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

        # we only need the JSON files
      - name: Get JSON PR files
        id: changed
        # get only the changed files
        run: |
          echo "files<<EOF" >> "$GITHUB_OUTPUT"
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '^assets/translations/.*\.json$' || true >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        

      - name: Validate
        if: steps.changed.outputs.files != ''
        run: |
          echo "Validating files: ${{ steps.changed.outputs.files }}"
          jq empty ${{ steps.changed.outputs.files }}
